### ISSUE TITLE
npm install vs node-gyp rebuild

### ISSUE THREAD

**Issue by kfiku** [atom/scrollbar-style#4]
I have another strange issue. First i need to add msvs_disabled_warnings 4244 (like https://github.com/atom/scrollbar-style/issues/3).
and next if i run `node-gyp rebuild` its ok but `npm install` or `npm build .` break with error:
```
> scrollbar-style@0.3.0 install c:\Portable\scrollbar-style
> node-gyp rebuild


c:\Portable\scrollbar-style>node "c:\Portable\nodejs\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild
gyp ERR! configure error
gyp ERR! stack Error: spawn ENOENT
gyp ERR! stack     at errnoException (child_process.js:998:11)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:789:34)
gyp ERR! System Windows_NT 6.0.6000
gyp ERR! command "node" "c:\\Portable\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd c:\Portable\scrollbar-style
gyp ERR! node -v v0.10.28
gyp ERR! node-gyp -v v0.13.0
gyp ERR! not ok

npm ERR! scrollbar-style@0.3.0 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the scrollbar-style@0.3.0 install script.
npm ERR! This is most likely a problem with the scrollbar-style package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls scrollbar-style
npm ERR! There is likely additional logging output above.
npm ERR! System Windows_NT 6.0.6000
npm ERR! command "c:\\portable\\nodejs\\node.exe" "c:\\portable\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install"
npm ERR! cwd c:\Portable\scrollbar-style
npm ERR! node -v v0.10.28
npm ERR! npm -v 1.4.9
npm ERR! code ELIFECYCLE
npm ERR!
npm ERR! Additional logging details can be found in:
npm ERR!     c:\Portable\scrollbar-style\npm-debug.log
npm ERR! not ok code 0
```

**Comment by tagisen** [comment]
@kfiku  I am having this issue as well. Did you manage to solve it?

**Comment by kevinsawicki** [comment]
The `stack Error: spawn ENOENT` message makes it seems like node wasn't available on your `PATH` when node-gyp ran `node "c:\Portable\nodejs\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js"` which is really strange and definitely shouldn't be happening.

It looks like maybe you are using a custom nodejs installation based on the `c:\\portable\\nodejs\\node.exe` part of the message so I'd make sure that your node folder is on your `PATH` and/or upgrade to a newer version of npm which may have fixed this issue.
